configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Fmet-museum-f5dcb30e8b0ca73656b44db0aedf802d9332d21d9b3c0c1f4c4370070b3ea8f3.yml
