configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Fmet-museum-1b8443a6bdc8469a424b4ce43646c098311fbec1fe1c02661ee03f58a02f1f95.yml
