configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Fmet-museum-83a8f3cb4ae7a94f5d19baeb97cd4bea1df220cccd84e4c4526d0c2450f9f368.yml
