configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Fmet-museum-0d48182f068fb99862fcefb292ed4fc8d1d74d9d63e1a17ef1a0f583daac9341.yml
